### ISSUE TITLE
Update rules to make it secure

### ISSUE THREAD

**Issue by rajaraodv** [echenley/react-news#23]
Currently, when the user logs in, they can write anything to $uid because there is no check to ensure they can write to only their own $uid bucket.
I think we should add:   ".write": "auth !== null && auth.uid === $uid" instead of !data.exists() 
```
  "users": {
      ".read": true,
      ".indexOn": ["username"],

      "$uid": {
        // user not authenticated until after profile is created
       // ".write": "!data.exists()",
        "write":  "auth !== null && auth.uid === $uid"
        "upvoted": {
          "$itemId": {
            ".write": "auth.uid === $uid"
          }
        },
        "submitted": {
          "$itemId": {
            ".write": "auth.uid === $uid"
          }
        }
      }
```

**Comment by echenley** [comment]
This wouldn't work since the user profile is created before the user is authenticated: https://github.com/echenley/react-news/blob/master/src/js/actions/Actions.js#L73

I did add some validation for initial profile data: https://github.com/echenley/react-news/commit/560bc05913f374601dac8f55b8a09cb15927cfb7
